### ISSUE TITLE
Sometimes the game ends and declares a winner prematurely

### ISSUE THREAD

**Issue by Muff1nz** [adamajammary/imt3601#105]

**Comment by adamajammary** [comment]
This should happen, when someone disconnects they are withdrawn from the match, until one player is left and the win screen will appear for the remaining player. But we can leave this issue open until we have fixed the root cause of why players get disconnected prematurely.

**Comment by Hifoz** [comment]
Probably same as #74

**Comment by adamajammary** [comment]
See #74 for more comments.

**Comment by adamajammary** [comment]
Hasn't happened in a while, will re-open or create a new issue if it happens again.
