### ISSUE TITLE
ERROR when someone dies and spectator mode is entered: "Tag: Spectator is not defined."

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#133]
Tag: Spectator is not defined.
UnityEngine.GameObject:set_tag(String)
SpectatorController:startSpectating() (at BunnyGame\Assets\Scripts\Spectator\SpectatorController.cs:69)
PlayerHealth:spectate() (at BunnyGame\Assets\Scripts\Player\PlayerHealth.cs:68)
PlayerHealth:showDeathScreen(GameOverMessage) (at BunnyGame\Assets\Scripts\Player\PlayerHealth.cs:317)
PlayerHealth:showGameOverScreen(GameOverMessage) (at BunnyGame\Assets\Scripts\Player\PlayerHealth.cs:273)
PlayerHealth:OnDeserialize(NetworkReader, Boolean)
UnityEngine.Networking.NetworkIdentity:OnUpdateVars(NetworkReader, Boolean) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkIdentity.cs:750)
UnityEngine.Networking.ClientScene:OnUpdateVarsMessage(NetworkMessage) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\ClientScene.cs:721)
UnityEngine.Networking.NetworkConnection:HandleReader(NetworkReader, Int32, Int32) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkConnection.cs:469)
UnityEngine.Networking.NetworkConnection:HandleBytes(Byte[], Int32, Int32) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkConnection.cs:425)
UnityEngine.Networking.NetworkConnection:TransportReceive(Byte[], Int32, Int32) (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkConnection.cs:576)
UnityEngine.Networking.NetworkClient:Update() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkClient.cs:753)
UnityEngine.Networking.NetworkClient:UpdateClients() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkClient.cs:965)
UnityEngine.Networking.NetworkIdentity:UNetStaticUpdate() (at C:\buildslave\unity\build\Extensions\Networking\Runtime\NetworkIdentity.cs:1091)

[C:\buildslave\unity\build\Runtime/Misc/GameObjectUtility.cpp line 1725] 
(Filename: BunnyGame/Assets/Scripts/Spectator/SpectatorController.cs Line: 69)

Suggestion to solution:
Just remove line 69 if the Spectator tag is not to be used, since the tag has not been created.

**Comment by Hifoz** [comment]
Is this on your working branch? This line has already been removed on the master branch because it ended up being unused

**Comment by adamajammary** [comment]
you're absolutely right
