### ISSUE TITLE
out of bounds exception thrown by trying to set AbilityNetwork._fireFart

### ISSUE THREAD

**Issue by Hifoz** [adamajammary/imt3601#137]
UnityException: Transform child out of bounds
AbilityNetwork.Start () (at Assets/Scripts/Abilities/AbilityNetwork.cs:30)

AbilityNetwork.cs:30:  

        this._fireFart = transform.GetChild(6).gameObject;

**Comment by adamajammary** [comment]
fixed in PR #140
