### ISSUE TITLE
Error when right-clicking to zoom and shoot.

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#14]
ERROR:

UnityException: Transform child out of bounds
PlayerController.HandleAiming () (at Assets/Scripts/PlayerController.cs:68)
PlayerController.HandleAiming () (at Assets/Scripts/PlayerController.cs:76)
PlayerController.Update () (at Assets/Scripts/PlayerController.cs:59)

SOLUTION:

Trying to access child index 1, but the player character has only 1 child.
Changed it to access child index 0 instead.

**Comment by Hifoz** [comment]
See comment on pull request  #12

**Comment by adamajammary** [comment]
Fixed, as Michael suggested, the minimap icon was missing.
