### ISSUE TITLE
Player is scaled in x and z but not in y when toggling minimap mode

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#15]
Is it supposed to do this?
If not, I will comment out these lines.

**File:**
Minimap.cs

**Code:**
case MinimapMode.FOLLOW_PLAYER:
   _player.transform.GetChild(0).localScale = new Vector3(3, 1, 3);

case MinimapMode.VIEW_ALL:
   _player.transform.GetChild(0).localScale = new Vector3(7, 1, 7);

**Comment by Hifoz** [comment]
See comment in your pull request #12 . The new playercharacter prefabs you added is missing the minimap icon, which this code relies on

**Comment by adamajammary** [comment]
Fixed, as Michael suggested, the minimap icon was missing.
