### ISSUE TITLE
Multiplayer character selection

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#20]
Only the two first connections get their selection, but remaining connections do not.
The problem is that the server needs to uniquely identify each connection, but using connectionId only worked for the two first connections (server/host got 0, and the rest got 1).

The second problem was that the client side sent the id of the player select canvas object available in the lobby, while the character creation in the lobby manager used the id of the lobby player.

**Solution:**
Used the unique netId of the lobby player on both the client and server side.

**Comment by Hifoz** [comment]
#21
