### ISSUE TITLE
Everyone won after one player died?

### ISSUE THREAD

**Issue by Hifoz** [adamajammary/imt3601#74]

**Comment by adamajammary** [comment]
Difficult to reproduce, should only happen when there is one player left on the server and that player is not already dead.

So at some point every one died exactly the same time and the player count became 1 left for everyone, very strange.

Tested with 6 players at once, placed them near the fire wall and watched all of them die with the correct you died message, except for the last player who got the winner message.

Will leave the issue open in case we experience it again in the next play test.

**Comment by adamajammary** [comment]
May have been fixed in PR #113, we'll see in the next play test.

**Comment by adamajammary** [comment]
NB!

I was able to reproduce the strange behavior that a winner was declared event though a player was still alive in the game, but not that all players won.

This happened when some players left and joined the lobby which messed up the counting of how many players were still alive in the game, this was refactored in PR #113.

**Comment by adamajammary** [comment]
Hasn't happened in a while, will re-open or create a new issue if it happens again.
