### ISSUE TITLE
Disconnecting from lobby/server makes it so you need to restart to create/join new lobby/server

### ISSUE THREAD

**Issue by Hifoz** [adamajammary/imt3601#81]
Currently we don't do anything to update the state of the lobbymanager when leaving a game/lobby, so the lobbymanager/matchmaker doesn't know we left, therefore making it so we cannot create or join a new lobby without restarting.

**Comment by Hifoz** [comment]
I am able to get this to partially work.

But no matter what I try, I can't seem to fix the issue where if you join a room as a client and then leave that room you cannot create a new room yourself. I can make it so the host can create a new room if he leaves his current one, and a client can join and leave as many rooms they want without problem unless as long as he doesn't try making a new room himself...

Supposedly, it should be enough to call StopHost() on the lobby manager, but for some reason it doesn't want to work...

**Comment by adamajammary** [comment]
Just noticed that you were working on the same as me :(
I have fixed the naming issue, and then started on the disconnect/connect issue as well.
Planning to complete it tomorrow, will let you know if I solve that issue as well.

**Comment by Hifoz** [comment]
Ah, then I'll let you handle this one, as I don't really know what more to try

**Comment by adamajammary** [comment]
See PR https://github.com/adamajammary/imt3601/pull/90

**Comment by Hifoz** [comment]
Resolved.
