### ISSUE TITLE
NWL loading makes player invincible during loading time

### ISSUE THREAD

**Issue by adamajammary** [adamajammary/imt3601#96]
Tested with 1 host and 5 clients, sometimes 2 or 3 clients started generating map when the game started.
While the loading took place the clients who were loading could not be attacked.

Suggestions:
- Force all other players to to wait until every ones loading has finished
- Load every one at the same time
- Handle game play and damage during load time
- ???

Not really sure what's best.

**Comment by Muff1nz** [comment]
Is the game normal once everyones finished loading? The cause for the bug is the fact that Time.timescale is set to 0 when loading, in order to pause the game, but the pause is only local ofcourse.

**Comment by adamajammary** [comment]
yes, everything is normal after the load finishes.

**Comment by Muff1nz** [comment]
Alright, making sure that the game is paused for every player until all loading is done would probably be the fairest solution, so that people don't get killed while loading.

**Comment by adamajammary** [comment]
Client sends message to server when loading data file
- Server tells all the clients that someone is loading

Client sends message to server with updated progress value
- Server tells all the clients the progress value of the slowet loading client
- Progress bar is shown and player control is disabled using PlayerController.setCC

Server tells all the clients when loading is complete
- Progress bar is hidden and player control is enabled

Firewall and NPC spawning waits for data file load to complete

Disabled attack and abilities during load time

**Comment by adamajammary** [comment]
Should be fixed in PR #190
